Table follows {
  following_user_id integer
  followed_user_id integer
  created_at timestamp
}

Table student {
  id integer [primary key]
  sam_account_name varchar
  registraire varchar
  emplid varchar
  oprid varchar
  password varchar
  profil_path varchar
  ou varchar
  city varchar
  id_student_edusign varchar
  lastname varchar
  firstname varchar
  principal_group varchar
  email_skema varchar
  email_perso varchar
  maj_date timestamp
  year varchar
  ppid varchar
  adrid varchar
  tpl17id varchar
  tpl36id varchar
  email_pro varchar
  gender varchar
  nationality varchar
  birthday_date timestamp
  birth_city varchar
  birth_department varchar
  phone_mobile varchar
  landline_mobile varchar
  postal_address varchar
  postal_code varchar
  postal_country varchar
  postal_city varchar
  principal_group_previous varchar
  principal_group_next varchar
  programm varchar
  speciality varchar
  academic_level varchar
  status varchar
  campus varchar
  acad_plan varchar
  acad_plan_descr varchar
  acad_plan_descr_short varchar
  acad_prog varchar
  acad_prog_descr varchar
  acad_prog_descr_short varchar
  acad_career varchar
  prog_action varchar
  prog_action_descr varchar
  prog_action_descr_short varchar
  program_eudonet varchar
  speciality_eudonet varchar
  param_custom varchar
  department varchar
  source varchar
  campus_origine varchar
  already_logged_in boolean
  date_already_logged_in varchar
  date_last_verif_logged_in varchar
  id_forma_sup varchar
  id_forma_sup_paris varchar
  id_forma_sup_sophia varchar
  citizenship_country varchar
  citizenship_status varchar
  origin varchar
  email_forma_sup varchar
  birth_country varchar
  id_edusign_france varchar
  id_edusign_belo varchar
  id_edusign_raleigh varchar
  id_edusign_dubai varchar
  id_edusign_suzhou varchar
}
